# **Introdução à Modelagem Econômica e Ciência de Dados (2022).**

# *Primeiro Trabalho - a ser devolvido ate o dia 21/10/2022.*

## **Exercício 1.** (15 pontos) Corrigindo um teste de múltipla escolha.

Escreva um código que calcule a nota de um teste de múltipla escolha contendo 5 questões (cada uma valendo 20 pontos). Cada questão possui 5 alternativas, nomeadas "a", "b", "c", "d" e "e". A resposta correta da primeira questão é "b", da segunda questão é "e", da terceira questão é "c", da quarta questão é "a" e da quinta questão é "d". Entre com a resposta de cada uma das questões e a seguir apresente a pontuação. O console deve imprimir a seguinte informação: 

`Entre com a resposta da questão 1: ___`

`Entre com a resposta da questão 2: ___`

`Entre com a resposta da questão 3: ___`

`Entre com a resposta da questão 4: ___`

`Entre com a resposta da questão 5: ___`

`O aluno fez ___ pontos.`

**Por exemplo:** Suponha que um aluno tenha respondido assim: primeira questão "a", segunda questão "e", terceira questão "d", quarta questão "b" e quinta questão "d". Neste caso o console irá imprimir:

`Entre com a resposta da questão 1: a`

`Entre com a resposta da questão 2: e`

`Entre com a resposta da questão 3: d`

`Entre com a resposta da questão 4: b`

`Entre com a resposta da questão 5: d`

`O aluno fez 40 pontos.`

In [ ]:
# Código Questão 1

# Atribuindo variáveis

quest1 = 'b'
quest2 = 'e'
quest3 = 'c'
quest4 = 'a'
quest5 = 'd'

answer1 = input("Entre com a resposta da questão 1: ") 
answer2 = input("Entre com a resposta da questão 2: ") 
answer3 = input("Entre com a resposta da questão 3: ") 
answer4 = input("Entre com a resposta da questão 4: ") 
answer5 = input("Entre com a resposta da questão 5: ") 

#Lista para receber valor de cada resposta

score = []

# Criando Condicionais de Acerto

if quest1 == answer1:
  score.append(5)
if quest2 == answer2:
  score.append(5)
if quest3 == answer3:
  score.append(5)
if quest4 == answer4:
  score.append(5)
if quest5 == answer5:
  score.append(5)

# Função para somar acertos

def final_score(score):
    total = 0
    for i in score:
       total = total + i
    return total

print('o aluno fez', final_score(score))

Entre com a resposta da questão 1: a
Entre com a resposta da questão 2: e
Entre com a resposta da questão 3: d
Entre com a resposta da questão 4: b
Entre com a resposta da questão 5: d
o aluno fez 10


## **Exercício 2.** (15 pontos) Construindo uma função que calcula o fatorial de um número.

Escreva um código que define uma função que permite calcular o fatorial de um número. A seguir pergunte um número para calcular seu fatorial. O console deve imprimir a seguinte informação:

`Entre um número: __X__`

`O fatorial de __X__ é __Y__.`

**Por exemplo:** Suponha que o número inserido seja `3`. Neste caso o console irá imprimir:

`Entre um número: 3`

`O fatorial de 3 é 6.`


In [ ]:
  x = int(input('Entre um número:',))
  y = 1
  for n in range(1,x+1):
    y *= n

print('o fatorial de', x, 'é', y)





Entre um número:3
o fatorial de 3 é 6


## **Exercício 3.** (15 pontos) Construindo uma função que calcula a sequencia de N números *Fibonacci*.

Escreva um código que define uma função que permite obter uma sequencia de Fibonacci com N números. A seguir pergunte um número N de elementos da sequencia de Fibonacci. O console deve imprimir a seguinte informação:

`Entre o número de elementos da sequencia de Fibonacci: __N__`

`A sequencia dos _N_ primeiros numeros de Fibonacci é: __F__.`

**Por exemplo:** Suponha que o número inserido seja `4`. Neste caso o console irá imprimir:

`Entre o número de elementos da sequencia de Fibonacci: 4`

`A sequencia dos _N_ primeiros numeros de Fibonacci é: 1, 1, 2, 3.`


In [ ]:
f0 = 0
f1 = 1
fN = int(input('Quantidade de números da sequencia:'))

c = 0

if fN <= 0:
  print('Error')
elif fN ==1:
  print(f1)
else:
  while c <fN:
    print(f1)

    f_new = f1+f0
    f0 = f1
    f1 = f_new
    c += 1






Quantidade de números da sequencia:7
1
1
2
3
5
8
13


## **Exercício 4.** (15 pontos) Saldo em carteira de fundos de investimentos.

Escreva um código, utilizando Numpy, que permite avaliar o saldo em carteira de fundos de investimentos de dois investidores. Em um certo dia, "Paulo" e "Cesar" possuiam, em suas respectivas carteiras, cotas de fundos de investimentos com as seguintes posições:

|Investidor|Renda Fixa|Ações|Multimercado|Cryptomoedas
|--|--|--|--|--|
|Paulo | 6| 3 |1 |0|
|Cesar | 9| 0|0|0.5|

O valor das cotas desses fundos ao final deste certo dia é o que segue: \$ 20.00 para o fundo de renda fixa, \$ 15.00 para o fundo de ações, \$ 18.00 para o fundo multimercado e \$ 6.00 para o fundo de cryptomoedas.

i. Utilizando Numpy, monte a matriz com as posições das carteiras de fundos de investimentos de "Paulo" e de "Cesar".

In [ ]:
import numpy as np

carteira = np.array([[6,3,1,0], [9,0,0,0.5]])
carteira


array([[6. , 3. , 1. , 0. ],
       [9. , 0. , 0. , 0.5]])

ii. Utilizando Numpy, monte uma matriz de valor das cotas de fechamento dos fundos (esta matriz deve possuir 4 linhas e 1 coluna).

In [ ]:
 cotas = np.array(np.mat('20 15 18 6'))

 matriz_1 = np.column_stack((cotas))

 matriz_1



array([[20],
       [15],
       [18],
       [ 6]])

iii. Utlizando Numpy, encontre o valor da carteira de fundos de investimentos de cada investidor.

In [ ]:
carteira.transpose()

value = np.dot(carteira, matriz_1)

value

array([[183.],
       [183.]])

Apresente no console a informação da seguinte forma:

`O valor da carteira de fundos de investimentos é de $ 183.00 para o Paulo e de $ 183.00 para o Cesar.`

In [ ]:
print('O valor da carteira de fundos de investimentos é de $', value[0,0], 'para o Paulo e de $', value[1,0], 'para o Cesar')



O valor da carteira de fundos de investimentos é de $ 183.0 para o Paulo e de $ 183.0 para o Cesar


## **Exercício 5.** (15 pontos) Alocação dos recursos em investimentos.

Escreva um código, utilizando Numpy, que permita determinar como um gestor deverá alocar os recursos entre fundos de investimentos. Suponha que este gestor tenha feito uma minunciosa análise e tenha concluido que dispõe de 3 fundos para poder alocar os recursos. O fundo A é o que apresenta risco mais elevado, o fundo B apresenta um risco intermediário e o fundo C apresenta baixo risco. De acordo com as projeções deste gestor, os retornos esperados para estes fundos são de: 20% a.a para o fundo A, 12.5% a.a. para o fundo B e 6% a.a. para o fundo C. Em sua análise para a gestão dos recursos o gestor decidiu que o montante que irá investir no fundo C deverá corresponder à soma do montante investido nos fundos A e B. Este gestor dispõe de \$ 100.00 para investir nos fundos A, B e C e o objetivo é o de alcançar um retorno de \$ 10.00. 

O console deverá irá imprimir:

`Montantes a serem alocados: fundo A = $ 10.00, fundo B = $ 40.00 e fundo C = $ 50.00.`

**Breve discussão sobre a estrutura do problema:** 

Sejam $x_A$, $x_B$ e $x_C$, respectivamente, os montantes a serem alocados nos fundos A, B e C. 

A partir do enunciado, temos que as restrições do problema são as seguintes:

$$ \left\{\begin{matrix}
0.2 x_A & + & 0.125 x_B & + & 0.06 x_C & = & 10 \\
-x_A & - & x_B & + & x_C & = &0 \\
x_A & + & x_B & + & x_C & = & 100
\end{matrix}\right |$$

Ou, de forma matricial, $$ Ax = B $$ onde:

$$ A = 
\begin{bmatrix} 
0.2 & 0.125 & 0.06 \\
 -1 & -1 & 1 \\
  1 & 1 & 1 
\end{bmatrix} $$, 
$$ x =
\begin{bmatrix} 
x_A \\
x_B \\
x_C 
\end{bmatrix} $$ 
e 
$$ B =
\begin{bmatrix} 
10 \\
0 \\
100 
\end{bmatrix} $$

Cuja solução será dada por: $$ x = A^{-1} B $$


In [ ]:
matrix = np.array([[0.2, 0.125, 0.06], [-1,-1,1], [1,1,1]])

matrix_b = np.array([[10],[0],[100]])

matrix_inv = np.linalg.inv(matrix)
x = np.linalg.solve(matrix,matrix_b)

print(x)

print('O Gestor deve alocar nos fundos A, B e C respectivamente',int(x[0,0]),int(x[1,0]), "e", int(x[2,0]))

[[10.]
 [40.]
 [50.]]
O Gestor deve alocar nos fundos A, B e C respectivamente 10 39 e 50


## **Exercício 6.** (15 pontos) Problema do consumidor.

Considere uma função de utilidade em relação a abacates (A) e barras de chocolate (B).

$$ U(A,B)=−(A−20)^2 −2(B−1)^2$$

Para calcular numericamente o máximo (que você provavelmente pode ver através da inspeção), deve-se resolver diretamente o problema de maximização restrita.

1. Encontre a cesta ótima quando $W = 10,\text{ }p_A = 1\text{, and }p_B = 2$.

2. Qual seria a cesta ótima se a renda passasse a ser de $W = 50$?

3. Qual seria a cesta ótima se a renda passasse a ser de $W = 150$?

## **Exercício 7.** (10 pontos) Problema livre de seu interesse.

Enuncie um problema de seu interesse e escreva um código que permita encontrar a solução. 

Calculando a distância entre dois pontos

In [ ]:
x1 = int(input("Valor do x1:"))
x2 = int(input("Valor do x2:"))
y1 = int(input("Valor do y1:"))
y2 = int(input("Valor do y2:"))

dist = (((x1-x2)**2+(y1-y2)**2)**0.5)

print(dist)

Valor do x1:3
Valor do x2:1
Valor do y1:4
Valor do y2:5
2.23606797749979
